# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "login": "Alex8@nmail.ru",
  "password": "12345678"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsInRva2VuSWQiOiI3NTkyNTQ2NS1kMmI2LTRjMmQtOTVhOS0wYzVhMTI5MTY3ZTQiLCJpYXQiOjE3MzY3MTc2MjUsImV4cCI6MTczOTMwOTYyNX0.Il46kJSepl7KvrHyVL3EFidT3oGw6K2wH_bj9OHrnc8

###

# Create a new post
POST http://localhost:3000/api/blogs/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsImlhdCI6MTczNzM5OTg0MCwiZXhwIjoxNzM3NDAwMTQwfQ.61qkWQO83jK_btZUDnZqXUg8gjngANDe6nhcDMQnxrc
Content-Type: application/json

{
  "postType": "text",
  "name": "Проверка не менее 20 символов",
  "preview": "Превью текста должно быть длинным около 50 символов",
  "text": " Текст поста нужно чтобы был аж 100 символов Текст поста нужно чтобы был аж 100 символов Текст поста нужно чтобы был аж 100 символов"
}

###

# Upload some file
POST http://localhost:3000/api/files/upload HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsImlhdCI6MTczNjg3NjQzNiwiZXhwIjoxNzM2ODc2NzM2fQ.BfSJ3hzHwZRok02AGhQ-WGJ0ME8m7ITxJsp_nwLJUk8
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="Загруженный файл.txt"

< ./users.controller.ts
--boundary--

###

# Get file by ID
GET http://localhost:3000/api/files/677e32f77b3864ac37c95875 HTTP/1.1

###

# Set like for post
POST http://localhost:3000/api/blogs/posts/fbcd1342-86ec-492a-ab51-f67ba760b8a7/likes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsImlhdCI6MTczNzQ3NDg2OSwiZXhwIjoxNzM3NDc1MTY5fQ.QExQFGvgN4B6uCfU8IaMEz1b2xSxAM20c-0MAD3nXMI
Content-Type: application/json

# Del like for post
DELETE http://localhost:3000/api/blogs/posts/fbcd1342-86ec-492a-ab51-f67ba760b8a7/likes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsImlhdCI6MTczNzQwMTExMCwiZXhwIjoxNzM3NDAxNDEwfQ.KkyMGcPeQU3wem5hRTxukRJgb7OA_9eU4UCQIAQiuGE
Content-Type: application/json


###
