# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "login": "Alex8@nmail.ru",
  "password": "12345678"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsInRva2VuSWQiOiI3NTkyNTQ2NS1kMmI2LTRjMmQtOTVhOS0wYzVhMTI5MTY3ZTQiLCJpYXQiOjE3MzY3MTc2MjUsImV4cCI6MTczOTMwOTYyNX0.Il46kJSepl7KvrHyVL3EFidT3oGw6K2wH_bj9OHrnc8

###

# Create a new post
POST http://localhost:3000/api/blog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsImlhdCI6MTczNjcyNTIzOSwiZXhwIjoxNzM2NzI1NTM5fQ.ye7bCfqnzVOlhtOBhgVkXMKjwgjWzQ5VUHtlIGW0Azo
Content-Type: application/json

{
  "postType": "text",
  "authorId": "6766fdb720f78014bf83d5a3",
  "name": "Проверка не менее 20 символов",
  "preview": "Превью текста должно быть длинным около 50 символов",
  "text": " Текст поста нужно чтобы был аж 100 символов Текст поста нужно чтобы был аж 100 символов Текст поста нужно чтобы был аж 100 символов"
}

###

# Upload some file
POST http://localhost:3000/api/files/upload HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzgzZmI1MzhkMzYxNzJkMzNiNWRkYTYiLCJlbWFpbCI6IkFsZXg4QG5tYWlsLnJ1IiwibG9naW4iOiJBbGV4OEBubWFpbC5ydSIsIm5hbWUiOiJBbGV4OCIsImlhdCI6MTczNjg3NjQzNiwiZXhwIjoxNzM2ODc2NzM2fQ.BfSJ3hzHwZRok02AGhQ-WGJ0ME8m7ITxJsp_nwLJUk8
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="Загруженный файл.txt"

< ./users.controller.ts
--boundary--

###

# Get file by ID
GET http://localhost:3000/api/files/677e32f77b3864ac37c95875 HTTP/1.1

###
