# Get all posts
GET http://localhost:3334/api/posts HTTP/1.1

###

# Get posts with filter

GET http://localhost:3334/api/posts?limit=2&sortDirection=desc&categories[]=39614113-7ad5-45b6-8093-06455437e1e2&page=1 HTTP/1.1

###

# Get post by id
GET http://localhost:3334/api/posts/50490a6c-e765-4e47-898b-1be3d5d61a6b HTTP/1.1

###

GET http://localhost:3334/api/posts/7e00699f-5847-45bb-9227-7c59190d0470 HTTP/1.1

###
# Create a new post
POST http://localhost:3334/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "postType": "text",
  "authorId": "6766fdb720f78014bf83d5a3",
  "name": "Первый пост не менее 20 символов",
  "preview": "Превью текста должно быть длинным около 50 символов",
  "text": " Текст поста нужно чтобы был аж 100 символов Текст поста нужно чтобы был аж 100 символов Текст поста нужно чтобы был аж 100 символов"
}

###

POST http://localhost:3334/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "postType": "video",
  "authorId": "6766fdb720f78014bf83d5a3",
  "tags": ["#Ford"],
  "name": "Первый пост не менее 20 символов",
  "url": "http://asd.ru"
  //"text": "gggf"
  }

###

# Delete the post by id
DELETE http://localhost:3334/api/posts/0549e0e7-ad8c-43b8-aa35-507ba547d743 HTTP/1.1

###

# Uncorrected Update post by id
PATCH http://localhost:3334/api/posts/142cb7ca-cd50-4110-8d2d-deee1ef8f223 HTTP/1.1
Content-Type: application/json

{
  "postType": "video",
  "name": "Это блог про кремль в г.Москва",
  "preview": "Предварительный",
  "description": "1"
}

###

# Update tags

PATCH http://localhost:3334/api/posts/fbe1e42f-d50b-475e-94d2-0e9c7eb13ca3 HTTP/1.1
Content-Type: application/json

{
  "postType": "text",
  "tags": ["#bus", "#bmw"]
}

###

# Create a new comment for post
POST http://localhost:3334/api/posts/142cb7ca-cd50-4110-8d2d-deee1ef8f223/comments HTTP/1.1
Content-Type: application/json

{
  "text": "This is text",
  "userId": "6766fdb720f78014bf83d5a3"
}

###
