# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "Alex@nmail.ru",
  "login": "Alexey",
  "name": "Alexey Ivanov",
  "password": "12345678"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/d675dcd53a64a8ba37facd5e1 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
